version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    command: sh -c "python manage.py runserver 0.0.0.0:8000 --settings=todoapp.settings.prod"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres-data: